services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    environment:
      DB_HOST: mysql_db
      DB_USER: app_user
      DB_PASS: ${DB_PASS}
      DB_NAME: ControlRoom
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ControlRoom
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:8081:80"
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    container_name: frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: sh -c "npm install && npm start"
    depends_on:
      - php

volumes:
  db_data:
  frontend_node_modules: