services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./uploads:/var/www/html/uploads
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    environment:
      DB_HOST: mysql_db
      DB_USER: app_user
      DB_PASS: app_pass
      DB_NAME: ControlRoom
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ControlRoom
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    restart: always

  frontend:
    image: node:20-alpine
    container_name: frontend
    restart: unless-stopped
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
      - frontend_node_modules:/var/www/frontend/node_modules
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
      - PORT=5173
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm start"

volumes:
  db_data:
  frontend_node_modules: