<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Victim extends \App\Entity\Victim implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null, 16],
        "\0".parent::class."\0".'gender' => [parent::class, 'gender', null, 16],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null, 16],
        "\0".parent::class."\0".'victimId' => [parent::class, 'victimId', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'firstname' => [parent::class, 'firstname', null, 16],
        'gender' => [parent::class, 'gender', null, 16],
        'lastname' => [parent::class, 'lastname', null, 16],
        'victimId' => [parent::class, 'victimId', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
