<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Assistance extends \App\Entity\Assistance implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'aidTeam' => [parent::class, 'aidTeam', null],
        "\0".parent::class."\0".'assistanceId' => [parent::class, 'assistanceId', null],
        "\0".parent::class."\0".'basicCareVPK' => [parent::class, 'basicCareVPK', null],
        "\0".parent::class."\0".'coordinator' => [parent::class, 'coordinator', null],
        "\0".parent::class."\0".'doctor' => [parent::class, 'doctor', null],
        "\0".parent::class."\0".'emergencyCare' => [parent::class, 'emergencyCare', null],
        'aidTeam' => [parent::class, 'aidTeam', null],
        'assistanceId' => [parent::class, 'assistanceId', null],
        'basicCareVPK' => [parent::class, 'basicCareVPK', null],
        'coordinator' => [parent::class, 'coordinator', null],
        'doctor' => [parent::class, 'doctor', null],
        'emergencyCare' => [parent::class, 'emergencyCare', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
