<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AidTeam extends \App\Entity\AidTeam implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'aidTeamId' => [parent::class, 'aidTeamId', null],
        "\0".parent::class."\0".'aidTeamName' => [parent::class, 'aidTeamName', null],
        "\0".parent::class."\0".'callNumber' => [parent::class, 'callNumber', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'event' => [parent::class, 'event', null],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        'aidTeamId' => [parent::class, 'aidTeamId', null],
        'aidTeamName' => [parent::class, 'aidTeamName', null],
        'callNumber' => [parent::class, 'callNumber', null],
        'description' => [parent::class, 'description', null],
        'event' => [parent::class, 'event', null],
        'isActive' => [parent::class, 'isActive', null],
        'status' => [parent::class, 'status', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
