<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Map extends \App\Entity\Map implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'event' => [parent::class, 'event', null, 16],
        "\0".parent::class."\0".'filePath' => [parent::class, 'filePath', null, 16],
        "\0".parent::class."\0".'mapEntities' => [parent::class, 'mapEntities', null, 16],
        "\0".parent::class."\0".'mapId' => [parent::class, 'mapId', null, 16],
        "\0".parent::class."\0".'mapType' => [parent::class, 'mapType', null, 16],
        'event' => [parent::class, 'event', null, 16],
        'filePath' => [parent::class, 'filePath', null, 16],
        'mapEntities' => [parent::class, 'mapEntities', null, 16],
        'mapId' => [parent::class, 'mapId', null, 16],
        'mapType' => [parent::class, 'mapType', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
