<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AidWorker extends \App\Entity\AidWorker implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'aidTeam' => [parent::class, 'aidTeam', null, 16],
        "\0".parent::class."\0".'aidWorkerId' => [parent::class, 'aidWorkerId', null, 16],
        "\0".parent::class."\0".'aidWorkerType' => [parent::class, 'aidWorkerType', null, 16],
        "\0".parent::class."\0".'callSign' => [parent::class, 'callSign', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'event' => [parent::class, 'event', null, 16],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'team' => [parent::class, 'team', null, 16],
        'aidTeam' => [parent::class, 'aidTeam', null, 16],
        'aidWorkerId' => [parent::class, 'aidWorkerId', null, 16],
        'aidWorkerType' => [parent::class, 'aidWorkerType', null, 16],
        'callSign' => [parent::class, 'callSign', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'event' => [parent::class, 'event', null, 16],
        'firstname' => [parent::class, 'firstname', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'lastname' => [parent::class, 'lastname', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'team' => [parent::class, 'team', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
