<?php

namespace DoctrineProxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AVPU extends \App\Entity\AVPU implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'AVPUId' => [parent::class, 'AVPUId', null, 16],
        "\0".parent::class."\0".'alert' => [parent::class, 'alert', null, 16],
        "\0".parent::class."\0".'pain' => [parent::class, 'pain', null, 16],
        "\0".parent::class."\0".'unresponsive' => [parent::class, 'unresponsive', null, 16],
        "\0".parent::class."\0".'verbal' => [parent::class, 'verbal', null, 16],
        'AVPUId' => [parent::class, 'AVPUId', null, 16],
        'alert' => [parent::class, 'alert', null, 16],
        'pain' => [parent::class, 'pain', null, 16],
        'unresponsive' => [parent::class, 'unresponsive', null, 16],
        'verbal' => [parent::class, 'verbal', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
